---

- name: Install PostgreSQL
  apt: name={{ item }} state=latest
  with_items:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python-psycopg2
  become: yes

- block:

  - name: Create application DB
    postgresql_db:
      name: "{{ db_name }}"
      encoding: UTF-8
      lc_collate: en_US.UTF-8
      lc_ctype: en_US.UTF-8

  - name: Create application DB user
    postgresql_user:
      db: "{{ db_name }}"
      name: "{{ db_user }}"
      password: "{{ db_user_password }}"

  become: yes
  become_user: postgres
