---
- hosts: all

  tasks:

  - name: install mc
    apt: name=mc state=latest
    become: yes
    become_method: sudo

  - name: update bash_profile
    template: src=bash_profile.j2 dest=~/.bash_profile

  - block:
    - name: install ufw
      apt: name=ufw state=latest
    - name: set firewall default policy
      ufw: state=enabled policy=reject
    - name: allow ssh
      ufw: rule=allow port=22 proto=tcp
    when: mode == "prod"
    become: yes
    become_method: sudo
